version: '3.4'
services:
  web:
    build:
      context: ./
      target: production
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-3122}:3122"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://db:27017/vly-prod
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
