version: '3.4'
services:
  web:
    build:
      context: ./
      # dockerfile: x/docker/Dockerfile
      target: development
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-3122}:3122"
    volumes:
      - ./assets:/usr/src/app/assets
      - ./components:/usr/src/app/components
      - ./config:/usr/src/app/config
      - ./hocs:/usr/src/app/hocs
      - ./lang:/usr/src/app/lang
      - ./lib:/usr/src/app/lib
      - ./pages:/usr/src/app/pages
      - ./server:/usr/src/app/server
      - ./static:/usr/src/app/static
      - ./.babelrc:/usr/src/app/.babelrc
      - ./next.config.js:/usr/src/app/next.config.js
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db:27017/vly-dev
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
